export enum StockSymbol {
    Bak = "BAK",
    Bel = "BEL",
    For = "FOR",
    Gra = "GRA",
    Her = "HER",
    LE = "LE,",
    Mcl = "MCL",
    Mil = "MIL",
    Mor = "MOR",
    Nel = "NEL",
    Nov = "NOV",
    Owe = "OWE",
    Pal = "PAL",
    Ros = "ROS",
    Smi = "SMI",
    StockSymbolLE = "LE",
    Stu = "STU",
    Whe = "WHE",
    Wri = "WRI",
}
